# Generated by Django 5.2.5 on 2025-08-08 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Undergarment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#FF6B6B', max_length=7)),
                ('material', models.CharField(choices=[('cotton', 'Cotton'), ('blend', 'Blend'), ('synthetic', 'Synthetic'), ('custom', 'Custom')], default='cotton', max_length=20)),
                ('custom_washes', models.IntegerField(default=60)),
                ('accessories', models.JSONField(default=list)),
                ('purchase_date', models.DateField()),
                ('wash_count', models.IntegerField(default=0)),
                ('retired', models.BooleanField(default=False)),
                ('retired_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undergarments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=20)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('undergarment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='api.undergarment')),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
    ]
